version: "3.9"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: docker.io/bitnami/kafka:3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest 
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  kafka-manager:
    image: mazahakq/kafka-manager:latest 
    build:
      context: ./
      dockerfile: ./kafka-manager/Dockerfile
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_MANAGER_AUTH_ENABLED: true
      KAFKA_MANAGER_USERNAME    : manager
      KAFKA_MANAGER_PASSWORD    : manager
      ZK_HOSTS                  : zookeeper:2181

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
